export const RouteDashboard:string = "/dashboard"
export const RouteDashboardOrders:string = RouteDashboard+"/orders"
export const RouteDashboardCustomers:string = RouteDashboard+"/customers"
export const RouteDashboardInventory:string = RouteDashboard+"/inventory"
export const RouteDashboardConversations:string = RouteDashboard+"/conversations"
export const RouteDashboardSettings:string = RouteDashboard+"/settings"
